name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build and push amd64
      uses: docker/build-push-action@v2
      with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: windyoc/ubuntu-development:latest
    - name: Build and push arm/v7
      uses: docker/build-push-action@v2
      with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm/v7
          push: true
          tags: windyoc/ubuntu-development:latest
    - name: Build and push arm64/v8
      uses: docker/build-push-action@v2
      with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64/v8
          push: true
          tags: windyoc/ubuntu-development:latest
    - name: Build and push ppc64le
      uses: docker/build-push-action@v2
      with:
          context: .
          file: ./Dockerfile
          platforms: linux/ppc64le
          push: true
          tags: windyoc/ubuntu-development:latest
    - name: Build and push s390x
      uses: docker/build-push-action@v2
      with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
          push: true
          tags: windyoc/ubuntu-development:latest

